# -*- coding: utf-8 -*-
"""DrebinSigAPI

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NalqcmJKsFbCLB50WimmVmwlp0q_tNsk
"""

import pandas as pd
import numpy as np
import csv

df = pd.read_csv("datasetfeaturescategories.xls")
df

print(df.columns)

df.value_counts(['model'])

apiCalls_condition = df['model'] == 'API call signature'
apiCalls_index = apiCalls_condition[apiCalls_condition == True].index
apiCalls_index

df_apiCalls = df[apiCalls_condition]
df_apiCalls

apiCalls = df_apiCalls['features'].tolist()

apiCalls

drebin215_completo = pd.read_csv("drebin215.xls")
drebin215_completo

drebin215_completo.columns.to_list()

drebin_sigapi = drebin215_completo.loc[:, apiCalls]
drebin_sigapi

drebin_sigapi['class'] = drebin215_completo['class']
drebin_sigapi

drebin_sigapi.info()

drebin_sigapi['class'].replace('B', 0, inplace = True)
drebin_sigapi['class'].replace('S', 1, inplace = True)

drebin_sigapi.value_counts('TelephonyManager.getSimCountryIso')

remove_index = list(np.where(drebin_sigapi['TelephonyManager.getSimCountryIso'] == '?'))
remove_index

drebin_sigapi.drop([ 176, 1971, 2109, 2950, 5174], inplace=True)

drebin_sigapi

drebin_sigapi['TelephonyManager.getSimCountryIso'] = drebin_sigapi['TelephonyManager.getSimCountryIso'].astype(str).astype(int)
drebin_sigapi

drebin_sigapi.info()

drebin_sigapi.isnull().values.any() #verifica se há NaN

drebin_sigapi

drebin_sigapi.to_csv('drebin_sigapi.csv', encoding='utf-8', index=False)

df = pd.read_csv("drebin_sigapi.csv")
df